### ISSUE TITLE
Domain name is not available in serverRuntime

### ISSUE THREAD

**Issue by ddsharpe** [oracle/weblogic-monitoring-exporter#13]
When monitoring more than one domain with Prometheus or Grafana, the data points need to to be keyed by domain name in order to keep data from each domain unique.  This is critical as it is impossible to monitor more than one domain with a given Prometheus instance without the data from all domains getting munged together.  For example, if you monitor the JVM heap of two domains where each domain has a managed server named "managed-1", each of the data points for those two servers are mixed together with no way to tell them apart.  This issue is not limited to server names, as almost anything could have the same name from one domain to the next, such as workmanagers, datasources, etc.  And for objects that don't have user-defined names, such as socket muxer, console app, etc, there is no workaround.

For example, the following exported stat will be identical for every domain that Prometheus monitors:
`wls_workmanager_completed_requests{name="ImageWorkManager"} 0
`
Unfortunately, the serverRuntime tree does not have its domain name anywhere that I can find. I am able to get the domain name from serverConfig, but that doesn't help since wls-exporter doesn't have that capability.

**Comment by moreaut** [comment]
To get the domain name using the WLS REST api, you need to send a GET request to the admin server (you can't get it from the managed server), e.g.:

   <adminserver host&port>/management/weblogic/edit?fields=name
 OR
   <adminserver host&port>/management/weblogic/domainConfig?fields=name
 OR
   <adminserver host&port>/management/weblogic/domainRuntime?fields=name

**Comment by moreaut** [comment]
I was wrong.  You can also get the domain name from the managed server's REST api by GET-ing
<managed server host& port>/management/weblogic/<version>/serverConfig?fields=name

**Comment by lilyhe123** [comment]
I'm not sure how easy to  add the server name to the exported data from the exporter, but we can take advantage of labels since both k8s and Prometheus support labels. 

As we know, when the wls operator creates a wls domain, it will add following labels to each created wls server pod: weblogic.domainUID=xxx, weblogic.clusterName=xxx, weblogic.serverName=xxx. And these labels can be added to Prometheus labels on metrics. In this way we can create query based on the domainName, clusterName, serverName.

See the dashboard snapshot I created in Grafana https://snapshot.raintank.io/dashboard/snapshot/Dia5JwjecaQap7QJ6c5WXyLCkJMBpbVg?orgId=2. This dashboard shows cpu loads on wls servers based on data scraped from wls-exporter. You can see the data has all the labels we needed.

The same thing goes to #14.

**Comment by russgold** [comment]
The exporter has no access to those labels, and is not aware of Kubernetes at all; it simply uses the WLS REST API. Whatever is available from the REST API can be added to the metrics.

**Comment by lilyhe123** [comment]
I don't mean we need the exporter to do this. The label mapping is done by the Prometheus  job which scraps data from k8s pod. See https://github.com/oracle/weblogic-monitoring-exporter/blob/05f1d3c4cc797577801df0ceceb9d92fc31718e8/samples/kubernetes/prometheus-deployment.yaml#L119. 

All I'm saying is that since we have ways to get domainName, clusterName, serverName we don't need to change the exporter to add this information.

**Comment by russgold** [comment]
Implemented by e16d6c4663a5f add support for domain name as a qualifier
