### ISSUE TITLE
ssrf

### ISSUE THREAD

**Issue by 360CodeSafe** [oracle/weblogic-monitoring-exporter#19]
HI!
I found a server-side request forgery vulnerability in the weblogic-monitoring-exporter project. The details are as follows:
Send a get request in the doGetRequest method of WebClientImpl.java
![图片](https://user-images.githubusercontent.com/39950310/56176924-5bb79c80-602f-11e9-9434-39caef2457c5.png)
The source of the url parameter is not reliable.The configuration information obtained by getServerName() and getServerPort() in MainServlet.java is unreliable, and the attacker can control the server to request forgery.
![图片](https://user-images.githubusercontent.com/39950310/56177017-c23cba80-602f-11e9-9bb4-98869119fb6c.png)

**Comment by russgold** [comment]
Thanks; can you explain why they are not reliable, and how an attacker can request forgery?

**Comment by 360CodeSafe** [comment]
![FQY0U}@16F}_V_MS _ASLW](https://user-images.githubusercontent.com/39950310/56253830-ae0cc200-60f0-11e9-8e04-b52ab5d506ea.png)
As shown in the above figure, when the attacker accesses "localhost:8080", the request is intercepted by using burp, and the host header is modified as the intranet ip. At this time, the string obtained by the background using "request.getServerName" is the intranet ip instead of "localhost".

**Comment by russgold** [comment]
I have created a pull request to address this issue. Since the exporter must use the server on which it is running, it will now always contact localhost. Presumably somebody could still counterfeit the port, but it seems much less likely for that to do anything useful. If you'd like to take a look, it is at

https://github.com/oracle/weblogic-monitoring-exporter/pull/23

**Comment by russgold** [comment]
Fixed by fd535a96c4e Use localhost to access REST API
